// src/lib/components/Aside/AsideMenu.svelte
<script lang="ts">
  import type { TRoute } from '$lib/client/routes';
  import AsideLink from './AsideLink.svelte';

  export let routes: TRoute[];

  export let classes: string = '';
</script>

<aside
  class={classes}
>
  <div
    class="flex flex-col w-40 overflow-y-auto max-w-40 bg-surfaceContainerHigh text-onSurface"
  >
    {#each routes as route}
      <AsideLink path={route.path} type={route.type} children={route.children} name={route.name} />
    {/each}
  </div>
</aside>

// project/app/lib/components/Aside/AsideMenu.tsx
import { FC } from "react";
import AsideLink from "./AsideLink";

type TRoute = {
  path: string;
  type: string;
  children?: TRoute[];
  name: string;
};

interface AsideMenuProps {
  routes: TRoute[];
  classes?: string;
}

const AsideMenu: FC<AsideMenuProps> = ({ routes, classes = "" }) => {
  return (
    <aside className={classes}>
      <div className="flex flex-col w-40 overflow-y-auto max-w-40 bg-surfaceContainerHigh text-onSurface">
        {routes.map((route) => (
          <AsideLink
            key={route.path}
            path={route.path}
            type={route.type}
            name={route.name}
          >
            {route.children}
          </AsideLink>
        ))}
      </div>
    </aside>
  );
};

export default AsideMenu;
