// project/app/lib/components/ThemeSwitcher.tsx
import { useEffect, useState } from "react";
import { MoonIcon, SunIcon } from "lucide-react";

const ThemeSwitcher = () => {
    const [theme, setTheme] = useState<string | null>(null);

    useEffect(() => {
        const storedTheme = localStorage.getItem("theme");
        setTheme(storedTheme);
        console.log(storedTheme);
    }, []);

    return (
        <div className="flex items-center justify-end">
            <label
                htmlFor="theme-switcher"
                className="p-2 cursor-pointer hover:bg-primaryContainer hover:text-onPrimaryContainer"
            >
                {theme === "light" ? (
                    <SunIcon id="theme-moon" />
                ) : theme === "dark" ? (
                    <MoonIcon id="theme-sun" />
                ) : null}
            </label>
        </div>
    );
};

export default ThemeSwitcher;

// svelte/src/lib/components/ThemeSwitcher.svelte
<script lang="ts">
  import { MoonIcon, SunIcon } from 'lucide-svelte';
  import { onMount } from 'svelte';

  let theme;
  onMount(() => {
    co
    theme = localStorage.getItem('theme') ?? '';
    console.log(theme);
  });
</script>

<div class="flex items-center justify-end">
  <label
    for="theme-switcher"
    class="p-2 cursor-pointer hover:bg-primaryContainer hover:text-onPrimaryContainer"
  >
    {#if theme === 'light'}
      <SunIcon id="theme-moon" />
    {:else if theme === 'dark'}
      <MoonIcon id="theme-sun" />
    {/if}
  </label>
</div>
<!-- 
{#if theme === 'light'}
  <div class="flex items-center justify-end">
    <label
      for="theme-switcher"
      class="p-2 cursor-pointer hover:bg-primaryContainer hover:text-onPrimaryContainer"
    >
      <SunIcon id="theme-moon" />
    </label>
  </div>
{:else if theme === 'dark'}
  <div class="flex items-center justify-end">
    <label
      for="theme-switcher"
      class="p-2 cursor-pointer hover:bg-primaryContainer hover:text-onPrimaryContainer"
    >
      <MoonIcon id="theme-sun" />
    </label>
  </div>
{:else}
  {null}
{/if} -->
