// project/app/lib/components/Aside/AsideLink.tsx
import { useLocation } from "@remix-run/react";
import clsx from "clsx";
import { useState, useEffect, FC } from "react";

interface AsideLinkProps {
  path: string;
  type: number | null;
  children?: AsideLinkProps[];
  name: string;
  indent?: number;
}

const AsideLink: FC<AsideLinkProps> = ({
  path,
  type,
  children = [],
  name,
  indent = 0,
}) => {
  const location = useLocation();
  const [isPath, setIsPath] = useState(false);

  useEffect(() => {
    setIsPath(location.pathname.includes(path));
  }, [location.pathname, path]);

  return (
    <div className="flex flex-col">
      {type === 2 && children.length > 0 ? (
        <>
          <input
            type="checkbox"
            className="hidden peer"
            id={path}
            checked={isPath}
            readOnly
          />
          <label
            className={clsx(
              "hover:bg- block cursor-pointer py-1.5 pl-3",
              isPath && "font-semibold text-primary"
            )}
            htmlFor={path}
          >
            {name}
          </label>

          <div
            className={clsx(
              "hidden flex-col peer-checked:flex",
              "bg-surfaceContainer"
            )}
          >
            {children.map((child, index) => (
              <AsideLink key={index} {...child} indent={indent + 1} />
            ))}
          </div>
        </>
      ) : type === 1 ? (
        <a
          className={clsx(
            "cursor-pointer py-2 pl-3 hover:underline",
            isPath && "font-semibold text-primary"
          )}
          href={path}
        >
          {name}
        </a>
      ) : null}
    </div>
  );
};

export default AsideLink;

// src/lib/components/Aside/AsideLink.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { uid } from 'uid';
  import clsx from 'clsx';
  export let path: string;
  export let type: number | null = null;
  export let children: any[] = [];
  export let name: string = '';
  export let indent: number = 0;
  $: isPath = $page.url.pathname.includes(path);
</script>

<div class='flex flex-col'>
{#if type === 2 && children.length > 0}
  <input type="checkbox" class={`hidden peer`} id={path} checked={isPath} />
  <label
    class={clsx(
      'hover:bg- block cursor-pointer py-1.5 pl-3',
      isPath && 'font-semibold text-primary'
    )}
    for={path}
  >
    {name}
  </label>

  <div class={clsx(`hidden flex-col peer-checked:flex`, `bg-surfaceContainer`)}>
    {#each children as child}
      <svelte:self {...child} indent={indent + 1} />
    {/each}
  </div>
{:else if type === 1}
  <a
    class={clsx(
      'cursor-pointer py-2 pl-3 hover:underline',
      isPath && 'font-semibold text-primary'
    )}
    href={path}>{name}</a
  >
{/if}
</div>
