// project/app/lib/components/FormSelect.tsx
import clsx from 'clsx';
import { FC } from 'react';

interface FormSelectProps extends React.SelectHTMLAttributes<HTMLSelectElement> {}

const FormSelect: FC<FormSelectProps> = ({ className, children, ...restProps }) => {
  return (
    <select
      className={clsx(
        ` 
        appearance-none rounded
        border border-outline
        bg-background
        px-2 py-1
        outline-none
        hover:border-primary
        focus:border-current focus:outline-primary focus:ring-0
        `,
        className
      )}
      {...restProps}
    >
      {children}
    </select>
  );
};

export default FormSelect;

// src/lib/components/FormSelect.svelte
<script lang="ts">
  import clsx from 'clsx';
  import type { HTMLSelectAttributes } from 'svelte/elements';

  export let label: string | null = null;
  interface $$Props extends HTMLSelectAttributes {
    label: string | null;
  }
</script>

{#if label}
  <label for={$$restProps.name}>{label}</label>
{/if}
<select
  class={clsx(
    `appearance-none border-solid border-outline rounded
    bg-background px-1.5
    py-0.5
    outline
    outline-1 outline-outline
    hover:border-primary hover:outline-primary
    focus:border-current focus:outline-primary focus:ring-current`,
    $$restProps.class
  )}
  name={$$restProps.name}
  value={$$restProps.value}
>
  <slot />
</select>
