// project/app/lib/components/FormButton.tsx
import clsx from 'clsx';
import { FC } from 'react';

interface FormButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string | undefined;
}

const FormButton: FC<FormButtonProps> = ({ className, children, ...restProps }) => {
  return (
    <button
      {...restProps}
      className={clsx(
        `
        appearance-none rounded
        border border-outline
        bg-background
        px-2 py-1
        outline-none
        hover:border-primary focus:border-current focus:outline-1 focus:outline-primary
        `,
        className
      )}
    >
      {children}
    </button>
  );
};

export default FormButton;

// src/lib/components/FormButton.svelte
<script lang="ts">
  import clsx from 'clsx';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  export let className: string | null = null;

  interface $$Props extends Omit<HTMLButtonAttributes, 'class'> {
    className?: string | null;
  }
</script>

<button
  {...$$restProps}
  class={clsx(
    `
    appearance-none rounded
    border border-outline
    bg-background
    px-2 py-1
    outline-none
    focus:border-current focus:outline-1 focus:outline-primary hover:border-primary
    `,
    $$restProps.class
  )}
>
  <slot />
</button>
